ALTER TABLE [dbo].[tblCS_Manufacturer]
    ADD CONSTRAINT [PK_tblCS_Manufacturer] PRIMARY KEY CLUSTERED ([ManufacturerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

