ALTER TABLE [dbo].[tblCS_Purchase]
    ADD CONSTRAINT [PK_tblCS_Purchase] PRIMARY KEY CLUSTERED ([PurchaseID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

