ALTER TABLE [dbo].[tblCS_Sale]
    ADD CONSTRAINT [PK_tblCS_Sale] PRIMARY KEY CLUSTERED ([SaleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

