ALTER TABLE [dbo].[tblCS_AppUserLogin]
    ADD CONSTRAINT [PK_tblCS_AppUserLogin] PRIMARY KEY CLUSTERED ([UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

