ALTER TABLE [dbo].[tblCS_Product_Size]
    ADD CONSTRAINT [PK_tblCS_Product_Size_1] PRIMARY KEY CLUSTERED ([ProductSizeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

